spring:
  datasource:
    # 驱动配置信息
    type: com.alibaba.druid.pool.DruidDataSource
    url:  jdbc:mysql://39.104.181.176:3306/ym_sale?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username:  wcitem
    password:  Yumo@wcupitem123
    url2:  jdbc:mysql://39.104.181.176:3306/ym_sale?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username2:  wcitem
    password2: Yumo@wcupitem123
    driverClassName: com.mysql.jdbc.Driver
    #连接池的配置信息
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
security:
  user:
    name: admin
    password: ymadmin
  basic:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@39.104.181.176:8759/eureka
  instance:
    preferIpAddress: true