server:
  port: 11000
security:
  user:
    name: admin
    password: admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.156:8761/eureka
  instance:
    preferIpAddress: true
#jasypt:
#  encryptor:
#    password: xxx